apiVersion: v1
kind: Namespace
metadata:
  name: chaos
  labels:
    app: chaos-monkey
    purpose: testing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-chaos-monkey-target
  namespace: chaos
  labels:
    app: chaos-monkey
    purpose: testing
spec:
  replicas: 5
  selector:
    matchLabels:
      app: chaos-monkey
      purpose: testing
  template:
    metadata:
      labels:
        app: chaos-monkey
        purpose: testing
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: dummy-chaos-monkey-target
        image: alpine
        command:
          - /bin/sh
          - -c
          - |
            sleep infinity
        imagePullPolicy: Always
        securityContext:
          runAsUser: 2000
          runAsGroup: 3000
          runAsNonRoot: true
          privileged: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - all
